DemoAspNetMvcCore/Models/ErrorViewModel.cs
using System;

namespace DemoAspNetMvcCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DemoAspNetMvcCore/Models/Filme.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DemoAspNetMvcCore.Models
{
    public class Filme
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "O campo Título é obrigatório")]
        [StringLength(60, MinimumLength = 6, ErrorMessage = "O Título precisa estar entre 6 e 60 caracteres")]
        public string Titulo { get; set; }

        [Required(ErrorMessage = "O campo Data de Lançamento é obrigatório")]
        [DataType(DataType.DateTime, ErrorMessage = "Data em formato incorreto")]
        [Display(Name = "Data de Lançamento")]
        public DateTime DataLancamento { get; set; }

        [Required(ErrorMessage = "Preencha o campo Gênero")]
        [StringLength(30,  MinimumLength = 5, ErrorMessage = "Mínimo de 5 e Máximo de 30 caracteres")]
        [Display(Name = "Genêro")]
        public string Genero { get; set; }

        [Required(ErrorMessage = "O campo Valor é obrigatório")]
        [Range(1,1000, ErrorMessage = "Valor de 1 a 1000")]
        [RegularExpression(@"[0-9]*$", ErrorMessage = "Somente números")]
        public decimal Valor { get; set; }

        [Required(ErrorMessage = "Preencha o campo Avaliação")]
        [RegularExpression(@"^[0-5]*$", ErrorMessage = "Somente números de 0 a 5")]
        [Display(Name = "Avaliação")]
        public int Avaliacao { get; set; }
    }
}

DemoAspNetMvcCore/Controllers/FilmesController.cs
using DemoAspNetMvcCore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoAspNetMvcCore.Controllers
{
    public class FilmesController : Controller
    {
        [HttpGet]
        public IActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Adicionar(Filme filme)
        {
            if (ModelState.IsValid)
            {
                //
            }

            return View(filme);
        }
    }
}

DemoAspNetMvcCore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DemoAspNetMvcCore.Models;

namespace DemoAspNetMvcCore.Controllers
{
    [Route("")]
    [Route("gestao-clientes")]
    public class HomeController : Controller
    {
        [Route("")]
        [Route("pagina-inicial")]
        [Route("pagina-inicial/{id:int}/{guid:guid}")]
        public IActionResult Index(int id, Guid guid)
        {
            return View();
        }

        [Route("privacidade")]
        [Route("politica-de-privacidade")]
        public IActionResult Privacy(Filme filme)
        {
            if(ModelState.IsValid)
            {

            }

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        [Route("error")]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DemoAspNetMvcCore/ViewComponents/CarrinhoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoAspNetMvcCore.ViewComponents
{
    [ViewComponent(Name = "Carrinho")]
    public class CarrinhoViewComponent : ViewComponent
    {
        public int quantidade;

        public CarrinhoViewComponent()
        {
            quantidade = 3;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(quantidade);
        }
    }
}

DemoAspNetMvcCore/Views/Filmes/Adicionar.cshtml
@model DemoAspNetMvcCore.Models.Filme

@{ 
    ViewData["Title"] = "Adicionar um filme";
}

<h3>@ViewData["Title"]</h3>

<div class="row">
    <div class="col-md-5">
        <form asp-action="Adicionar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="@Model.Titulo" class="control-label"></label>
                <input asp-for="@Model.Titulo" class="form-control" />
                <span asp-validation-for="@Model.Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.DataLancamento" class="control-label"></label>
                <input asp-for="@Model.DataLancamento" class="form-control" />
                <span asp-validation-for="@Model.DataLancamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Genero" class="control-label"></label>
                <input asp-for="@Model.Genero" class="form-control" />
                <span asp-validation-for="@Model.Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Valor" class="control-label"></label>
                <input asp-for="@Model.Valor" class="form-control" />
                <span asp-validation-for="@Model.Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Avaliacao" class="control-label"></label>
                <input asp-for="@Model.Avaliacao" class="form-control" />
                <span asp-validation-for="@Model.Avaliacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Adicionar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts
{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); } 
}

DemoAspNetMvcCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<partial name="_AvisoGeral" />

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DemoAspNetMvcCore/Views/Shared/Components/Carrinho/Default.cshtml
@model int;

<i class="fa fa-shopping-cart" aria-hidden="true"></i>&nbsp;@Model

DemoAspNetMvcCore/Views/Shared/_AvisoGeral.cshtml
<div id="avisoGeral" class="alert alert-info alert-dismissible fade show" role="alert">
    Partial View Aviso Geral.
</div>

DemoAspNetMvcCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoAspNetMvcCore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoAspNetMvcCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Filmes" asp-action="Adicionar">Adicionar Filmes</a>
                        </li>
                    </ul>
                </div>
                <vc:Carrinho></vc:Carrinho>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DemoAspNetMvcCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/lib/font-awesome/js/all.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>